seed: 42
debug: false
print_freq: 100
num_workers: 4
clip_type: "random"
OUTPUT_DIR: "./"

train_datadir: "./data/raw/birdclef-2025/train_audio"
train_csv: "./data/processed/train_preprocess_with_human_voice_filter0.5.csv"
submission_csv: "./data/raw/birdclef-2025/sample_submission.csv"
taxonomy_csv: "./data/raw/birdclef-2025/taxonomy.csv"

model_name: "seresnext26t_32x4d"
pretrained: true
in_channels: 1

LOAD_DATA: true 
FS: 32000
TARGET_DURATION: 5.0
TRAIN_DURATION: 7.0
    
N_FFT: 2048
HOP_LENGTH: 512
N_MELS: 256
FMIN: 20
FMAX: 16000

device: "auto"
epochs: 30
batch_size: 32
criterion: "FocalLossCE"
normal: 80
n_fold: 5
selected_folds: [0]

optimizer: "AdamW"
lr: 0.0005
weight_decay: 0.00001

scheduler: "CosineAnnealingLR"
min_lr: 0.000001
T_max: 30

mixup_prob: 0.1
mixup_double: 1.0
mix_beta: 5
mix_beta2: 2
mixup2_prob: 0.7
mixup: false
mixup2: true
cutmix: false
